// Linked secondary Google Drive accounts used as manual backup destinations.
// Deliberately separate from oauth_accounts: this is not a login identity,
// just a Drive grant a bucket owner controls.

import type { Database } from "bun:sqlite";
import { nowIso } from "../../util/ids.ts";

export type BackupAccountStatus = "active" | "reauthorization_required" | "error";

export interface BackupAccountRow {
  id: string;
  owner_user_id: string;
  email: string;
  encrypted_refresh_token: string;
  granted_scopes: string;
  root_folder_id: string | null;
  status: BackupAccountStatus;
  last_error: string | null;
  last_used_at: string | null;
  created_at: string;
  updated_at: string;
}

export class BackupAccountsRepository {
  constructor(private readonly db: Database) {}

  findById(id: string): BackupAccountRow | null {
    return this.db.query<BackupAccountRow, [string]>("SELECT * FROM backup_accounts WHERE id = ?").get(id) ?? null;
  }

  findOwned(ownerUserId: string, id: string): BackupAccountRow | null {
    return (
      this.db
        .query<BackupAccountRow, [string, string]>(
          "SELECT * FROM backup_accounts WHERE id = ? AND owner_user_id = ?",
        )
        .get(id, ownerUserId) ?? null
    );
  }

  listByOwner(ownerUserId: string): BackupAccountRow[] {
    return this.db
      .query<BackupAccountRow, [string]>(
        "SELECT * FROM backup_accounts WHERE owner_user_id = ? ORDER BY created_at ASC",
      )
      .all(ownerUserId);
  }

  /** id is generated by the caller so it can be bound into the refresh
   * token's encryption AAD before the row exists. */
  create(input: {
    id: string;
    ownerUserId: string;
    email: string;
    encryptedRefreshToken: string;
    grantedScopes: string;
  }): BackupAccountRow {
    const { id } = input;
    const now = nowIso();
    this.db
      .query(
        `INSERT INTO backup_accounts
           (id, owner_user_id, email, encrypted_refresh_token, granted_scopes, status, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, 'active', ?, ?)`,
      )
      .run(id, input.ownerUserId, input.email, input.encryptedRefreshToken, input.grantedScopes, now, now);
    return this.findById(id)!;
  }

  /** null clears the cache, so the next ensure re-resolves or recreates the
   *  folder rather than uploading into an id that no longer exists. */
  setRootFolder(id: string, rootFolderId: string | null): void {
    this.db
      .query("UPDATE backup_accounts SET root_folder_id = ?, updated_at = ? WHERE id = ?")
      .run(rootFolderId, nowIso(), id);
  }

  markRefreshed(id: string): void {
    const now = nowIso();
    this.db
      .query(
        "UPDATE backup_accounts SET status = 'active', last_error = NULL, last_used_at = ?, updated_at = ? WHERE id = ?",
      )
      .run(now, now, id);
  }

  markError(id: string, status: BackupAccountStatus, error: string): void {
    const now = nowIso();
    this.db
      .query("UPDATE backup_accounts SET status = ?, last_error = ?, updated_at = ? WHERE id = ?")
      .run(status, error, now, id);
  }

  delete(ownerUserId: string, id: string): boolean {
    return (
      this.db.query("DELETE FROM backup_accounts WHERE id = ? AND owner_user_id = ?").run(id, ownerUserId)
        .changes > 0
    );
  }
}
